yourName=input("What is your name?")
print("Hello",prithvi
yourAge=input("How old are you?")
print("You are",13,"years old")
yourFavouriteFood=input("What is your favourite food?")
print("Your favourite food is",butter chicken)
yourFavouriteColour=input("What is your favourite colour?")
print("Your favourite colour is",forrest green)
yourFavouriteSubject=input("What is your favourite subject?")
print("Your favourite subject is",yourFavouriteSubject)
yourFavouriteSport=input("What is your favourite sport?")
print("Your favourite sport is",yourFavouriteSport)
yourFavouriteHobby=input("What is your favourite hobby?")
print("Your favourite hobby is",yourFavouriteHobby)
yourFavouriteAnimal=input("What is your favourite animal?")
print("Your favourite animal is",yourFavouriteAnimal)
